local:
  user-workflow:
    workflow-name: "aura-protocol-rwa-ingestion"
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.json"
    secrets-path: "./secrets.yaml"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
