name: "aura-protocol-rwa-ingestion"
version: "2.0.0"

# Secrets management
secrets:
  - name: ALPHA_VANTAGE_API_KEY
    reference: ALPHA_VANTAGE_API_KEY
    required: true

# HTTP Capability for external API calls
capabilities:
  - id: http-actions@1.0.0-alpha
    permissions:
      - domain: www.alphavantage.co
        methods: [GET]
        paths: ["/query"]

# Triggers
triggers:
  - id: cron-trigger
    type: cron
    config:
      schedule: "*/5 * * * *"

# Runtime configuration
runtime:
  wasm:
    enabled: true
    memory: 128MB
  timeout: 30s
