name: "aura-protocol-rwa-ingestion"
version: "2.0.0"

# Secrets management
secrets:
  - name: ALPHA_VANTAGE_API_KEY
    reference: ALPHA_VANTAGE_API_KEY
    required: true

# HTTP Capability for external API calls (2026 CRE SDK format)
capabilities:
  - id: http@1.0.0
    config:
      allowed_hosts:
        - www.alphavantage.co
      allowed_methods:
        - GET
      max_response_size_bytes: 1048576  # 1MB
      timeout_ms: 30000

# Triggers
triggers:
  - id: cron-trigger
    type: cron
    config:
      schedule: "*/5 * * * *"

# Runtime configuration
runtime:
  wasm:
    enabled: true
    memory: 128MB
  timeout: 30s
